apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: feedless-ingress
spec:
  rules:
    - host: api.staging.feedless.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: feedless-core
                port:
                  number: 8080
    - host: staging.feedless.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: feedless-web
                port:
                  number: 80
