apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: feedless-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: api.feedless.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: feedless-core
                port:
                  number: 8080
    - host: feedless.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: feedless-web
                port:
                  number: 80
