apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plausible-ingress
  annotations:
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: plausible-basic-auth
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
spec:
  ingressClassName: nginx
  rules:
    - host: plausible.feedless.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: plausible-service
                port:
                  number: 80
