apiVersion: v1
kind: ConfigMap
metadata:
  name: plausible-env
data:
  BASE_URL: "https://feedles.org"
  # see https://github.com/plausible/community-edition/tree/v2.1.0?tab=readme-ov-file#secret_key_base
  SECRET_KEY_BASE: "<generate: openssl rand -base64 64>"
  TOTP_VAULT_KEY: "<generate: openssl rand -base64 32>"

---

apiVersion: v1
kind: Secret
metadata:
  name: plausible-db-user
type: Opaque
stringData:
  username: "admin"
  password: "admin"

---

apiVersion: v1
kind: Secret
metadata:
  name: plausible-events-db-user
type: Opaque
stringData:
  username: "admin"
  password: "admin"
