# https://grafana.com/docs/loki/latest/send-data/promtail/installation/
# helm upgrade --values values.yaml --install promtail grafana/promtail
config:
  clients:
    - url: http://loki.default.svc.cluster.local:3100/loki/api/v1/push

  scrape_configs:
    - job_name: kubernetes
      kubernetes_sd_configs:
        - role: pod  # Scraping logs from Kubernetes Pods
      relabel_configs:
        - source_labels: [ __meta_kubernetes_pod_label_app ]
          target_label: app
        - source_labels: [ __meta_kubernetes_namespace ]
          target_label: namespace
        - source_labels: [ __meta_kubernetes_pod_name ]
          target_label: pod
        - source_labels: [ __meta_kubernetes_pod_container_name ]
          target_label: container
      pipeline_stages:
        - docker: { }  # Optional, for parsing Docker logs
        - multiline:
            firstline: '^[[:space:]]'
            separator: '^[[:space:]]'
      static_configs:
        - targets:
            - localhost  # The target is localhost for scraping from within the pod
          labels:
            job: kubernetes-pods
            __path__: /var/log/containers/*.log

    - job_name: system
      static_configs:
        - targets:
            - localhost
          labels:
            job: system-logs
            __path__: /var/log/*log  # Path to system logs (optional)

