package org.migor.rss.rich

import org.migor.rss.rich.model.*
import org.migor.rss.rich.repository.*
import org.slf4j.LoggerFactory
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.context.annotation.Configuration
import org.springframework.context.annotation.Profile
import org.springframework.stereotype.Component
import java.time.temporal.ChronoUnit
import javax.annotation.PostConstruct


@Configuration
class Initializer {

  @Component
  @Profile("dev")
  class DevInitializer {

    val log = LoggerFactory.getLogger("DevInitializer")

    @Autowired
    lateinit var subscriptionRepository: SubscriptionRepository

    @Autowired
    lateinit var subscriptionGroupRepository: SubscriptionGroupRepository

    @Autowired
    lateinit var userRepository: UserRepository

    @Autowired
    lateinit var sourceRepository: SourceRepository

    @Autowired
    lateinit var feedRepository: FeedRepository

    @PostConstruct
    fun init() {

      var user1 = User()
      user1.apiKey = "key1"
      user1.name = "foo"
      user1.emailHash = CryptUtil.sha1("foo@bar")
      user1.description = "Senior Software Engineering"
      userRepository.save(user1)

      user1.feeds = listOf(
        feedRepository.save(Feed("activity", user1, AccessPolicy.PROTECTED, 1)),
//        feedRepository.save(Feed("queue", user1, AccessPolicy.NONE, 2)),
        feedRepository.save(Feed("sink", user1, AccessPolicy.PUBLIC))
      )
      user1 = userRepository.save(user1)


      var user2 = User()
      user2.apiKey = "key2"
      user2.name = "bar"
      user2.emailHash = CryptUtil.sha1("bar@foo")
      user2.description = "Learning | Focussing | Living"
      user2 = userRepository.save(user2)

      user2.feeds = listOf(
        feedRepository.save(Feed("activity", user2, AccessPolicy.PROTECTED, 1)),
//        feedRepository.save(Feed("queue", user2, AccessPolicy.NONE, 2)),
        feedRepository.save(Feed("sink", user2, AccessPolicy.PUBLIC))
      )
      userRepository.save(user2)

      val source1 = sourceRepository.save(Source("https://lemire.me/blog/feed/"))
      val source2 = sourceRepository.save(Source("https://www.lesswrong.com/feed.xml?view=curated-rss"))
      val sub1 = subscriptionRepository.save(Subscription(user1, source1))
      val subscription = Subscription(user1, source2)
      subscription.throttled = true
      subscription.releaseBatchSize = 2
      subscription.releaseInterval = 1
      subscription.releaseTimeUnit = ChronoUnit.DAYS
      val sub2 = subscriptionRepository.save(subscription)
      val group1 = subscriptionGroupRepository.save(SubscriptionGroup("tech", user1))
      sub1.group = group1
      subscriptionRepository.save(sub1)
      sub2.group = group1
      subscriptionRepository.save(sub2)

      val source3 = sourceRepository.save(Source("http://brett.trpstra.net/brettterpstra"))
      val sub3 = subscriptionRepository.save(Subscription(user2, source3))
      val source4 = sourceRepository.save(Source("https://www.heise.de/rss/heise.rdf"))
      val sub4 = subscriptionRepository.save(Subscription(user2, source4))
      val source5 = sourceRepository.save(Source("https://www.heise.de/tp/news-atom.xml"))
      val sub5 = subscriptionRepository.save(Subscription(user2, source5))
      val source6 = sourceRepository.save(Source("https://www.derstandard.at/rss/inland"))
      val sub6 = subscriptionRepository.save(Subscription(user2, source6))
      sub6.takeIf = "not(endsWith(title, '?'))"

      val group2 = subscriptionGroupRepository.save(SubscriptionGroup("tech", user2))
      sub3.group = group2
      subscriptionRepository.save(sub3)

      val group3 = subscriptionGroupRepository.save(SubscriptionGroup("news", user2))
//      sub4.group = group3
//      subscriptionRepository.save(sub3)
      sub5.group = group3
      subscriptionRepository.save(sub5)

      sourceRepository.save(Source("https://developers.500px.com/feed"))
      sourceRepository.save(Source("https://8thlight.com/blog/feed/atom.xml"))
      sourceRepository.save(Source("https://99designs.com/tech-blog/feed.xml"))
      sourceRepository.save(Source("http://tech.adroll.com/feed.xml"))
      sourceRepository.save(Source("https://medium.com/feed/build-addepar"))
      sourceRepository.save(Source("https://build.affinity.co/feed"))
      sourceRepository.save(Source("https://airbrake.io/blog/feed"))
      sourceRepository.save(Source("https://www.airpair.com/rss"))
      sourceRepository.save(Source("https://advancedweb.hu/atom.xml"))
      sourceRepository.save(Source("https://medium.com/feed/airbnb-engineering"))
      sourceRepository.save(Source("https://airtame.engineering/feed"))
      sourceRepository.save(Source("https://blog.algolia.com/feed/"))
      sourceRepository.save(Source("https://allegro.tech/feed.xml"))
      sourceRepository.save(Source("https://techblog.appnexus.com/feed"))
      sourceRepository.save(Source("http://blog.arkency.com/atom.xml"))
      sourceRepository.save(Source("http://artsy.github.io/feed"))
      sourceRepository.save(Source("https://blog.asana.com/feed/"))
      sourceRepository.save(Source("https://developer.atlassian.com/blog/feed.xml"))
      sourceRepository.save(Source("https://spin.atomicobject.com/feed/"))
      sourceRepository.save(Source("https://auth0.com/blog/rss.xml"))
      sourceRepository.save(Source("http://blog.avenuecode.com/rss.xml"))
      sourceRepository.save(Source("https://aws.amazon.com/blogs/aws/feed/"))
      sourceRepository.save(Source("https://www.azavea.com/blog/category/software-development/rss"))
      sourceRepository.save(Source("https://blog.babbel.com/en/feed/"))
      sourceRepository.save(Source("https://backtrace.io/feed/"))
      sourceRepository.save(Source("https://techblog.badoo.com/feed.xml"))
      sourceRepository.save(Source("https://bandcamptech.wordpress.com/feed/"))
      sourceRepository.save(Source("https://lab.getbase.com/feed/"))
      sourceRepository.save(Source("https://blog.developer.bazaarvoice.com/feed/"))
      sourceRepository.save(Source("https://medium.com/feed/bbc-design-engineering"))
      sourceRepository.save(Source("https://benchling.engineering/feed"))
      sourceRepository.save(Source("https://www.benefitfocus.com/rss.xml"))
      sourceRepository.save(Source("https://www.bigeng.io/rss/"))
      sourceRepository.save(Source("https://binary-studio.com/blog/rss"))
      sourceRepository.save(Source("https://word.bitly.com/rss"))
      sourceRepository.save(Source("https://engineering.bittorrent.com/feed/"))
      sourceRepository.save(Source("https://medium.com/feed/blablacar-tech"))
      sourceRepository.save(Source("http://rockthecode.io/feed/"))
      sourceRepository.save(Source("https://code.blender.org/rss"))
      sourceRepository.save(Source("http://engineering.blogfoster.com/rss/"))
      sourceRepository.save(Source("http://engineering.bloomreach.com/feed/"))
      sourceRepository.save(Source("https://www.box.com/blog/feed"))
      sourceRepository.save(Source("https://www.boxever.com/feed/"))
      sourceRepository.save(Source("https://engineering.brandwatch.com/rss/"))
      sourceRepository.save(Source("https://tech.buzzfeed.com/feed"))
      sourceRepository.save(Source("https://product.canva.com/feed.xml"))
      sourceRepository.save(Source("https://capgemini.github.io/feed.xml"))
      sourceRepository.save(Source("https://www.ctl.io/developers/blog/rss"))
      sourceRepository.save(Source("http://engineering.cerner.com/atom.xml"))
      sourceRepository.save(Source("https://blog.chaps.io/feed.xml"))
      sourceRepository.save(Source("http://engineering.chartbeat.com/feed/"))
      sourceRepository.save(Source("https://blog.chef.io/rss"))
      sourceRepository.save(Source("https://engineering.clever.com/rss"))
      sourceRepository.save(Source("https://clevertap.com/blog/tag/engineering/feed/"))
      sourceRepository.save(Source("https://www.cloudbees.com/blog.xml"))
      sourceRepository.save(Source("https://blog.cloudera.com/feed/"))
      sourceRepository.save(Source("https://blog.cloudflare.com/rss/"))
      sourceRepository.save(Source("https://www.cockroachlabs.com/blog/index.xml"))
      sourceRepository.save(Source("http://feeds.feedburner.com/CodeBetter"))
      sourceRepository.save(Source("https://www.codelitt.com/blog/rss"))
      sourceRepository.save(Source("https://crypt.codemancers.com/index.xml"))
      sourceRepository.save(Source("https://www.codementor.io/tutorial/feed"))
      sourceRepository.save(Source("http://www.codenameone.com/feed.xml"))
      sourceRepository.save(Source("http://blog.codeship.com/feed/"))
      sourceRepository.save(Source("https://engineering.coinbase.com/feed"))
      sourceRepository.save(Source("https://collectiveidea.com/blog/feed/"))
      sourceRepository.save(Source("https://techblog.commercetools.com/feed"))
      sourceRepository.save(Source("https://technology.condenast.com/feed/rss"))
      sourceRepository.save(Source("https://www.confluent.io/feed/"))
      sourceRepository.save(Source("https://convox.com/blog/rss.xml"))
      sourceRepository.save(Source("https://devblog.coolblue.nl/feed/"))
      sourceRepository.save(Source("http://engineering.criteolabs.com/feeds/posts/default"))
      sourceRepository.save(Source("https://crowdfire.engineering/feed"))
      sourceRepository.save(Source("http://engineering.curalate.com/feed.xml"))
      sourceRepository.save(Source("https://medium.com/feed/dailymotion-engineering"))
      sourceRepository.save(Source("https://data-artisans.com/feed"))
      sourceRepository.save(Source("https://databricks.com/feed"))
      sourceRepository.save(Source("https://eng.datafox.com/feed.xml"))
      sourceRepository.save(Source("https://deezer.io/feed"))
      sourceRepository.save(Source("https://deferpanic.com/blog/index.xml/"))
      sourceRepository.save(Source("https://deis.com/feed.xml"))
      sourceRepository.save(Source("http://deliveroo.engineering/feed.xml"))
      sourceRepository.save(Source("https://www.digitalocean.com/community/tutorials/feed"))
      sourceRepository.save(Source("https://blog.discordapp.com/feed"))
      sourceRepository.save(Source("https://blog.docker.com/feed/"))
      sourceRepository.save(Source("https://medium.com/feed/doordash-blog/tagged/engineering"))
      sourceRepository.save(Source("https://drivy.engineering/feed.xml"))
      sourceRepository.save(Source("https://blogs.dropbox.com/tech/feed/"))
      sourceRepository.save(Source("https://www.ebayinc.com/stories/news/rss/"))
      sourceRepository.save(Source("https://medium.com/feed/unexpected-token"))
      sourceRepository.save(Source("https://www.eharmony.com/engineering/feed/"))
      sourceRepository.save(Source("https://www.elastic.co/blog/feed"))
      sourceRepository.save(Source("https://blog.engineyard.com/feed.xml"))
      sourceRepository.save(Source("https://sourcecode.entelo.com/feed.xml"))
      sourceRepository.save(Source("https://webuild.envato.com/atom.xml"))
      sourceRepository.save(Source("https://envoy.engineering/feed"))
      sourceRepository.save(Source("https://www.erlang-solutions.com/news.rss"))
      sourceRepository.save(Source("https://codeascraft.com/feed/"))
      sourceRepository.save(Source("https://www.eventbrite.com/engineering/feed/"))
      sourceRepository.save(Source("https://evernote.com/blog/feed/"))
      sourceRepository.save(Source("https://evilmartians.com/chronicles.atom"))
      sourceRepository.save(Source("https://techblog.expedia.com/feed/"))
      sourceRepository.save(Source("https://code.fb.com/feed/"))
      sourceRepository.save(Source("https://research.fb.com/feed/"))
      sourceRepository.save(Source("https://blog.faraday.io/rss/"))
      sourceRepository.save(Source("https://medium.com/feed/feedzaitech"))
      sourceRepository.save(Source("http://making.fiftythree.com/feed.xml"))
      sourceRepository.save(Source("https://tech.findmypast.com/feed.xml"))
      sourceRepository.save(Source("http://tech.finn.no/atom.xml"))
      sourceRepository.save(Source("https://dev.firmafon.dk/blog/feed.xml"))
      sourceRepository.save(Source("http://code.flickr.net/feed/"))
      sourceRepository.save(Source("http://engineering.flipboard.com/feed.xml"))
      sourceRepository.save(Source("https://engineering.foursquare.com/feed"))
      sourceRepository.save(Source("https://freeletics.engineering/feed.xml"))
      sourceRepository.save(Source("https://engineering.fundingcircle.com/blog/feed.xml"))
      sourceRepository.save(Source("https://www.future-processing.pl/technical-blog/rss"))
      sourceRepository.save(Source("https://galois.com/feed/"))
      sourceRepository.save(Source("http://tech.gc.com/atom.xml"))
      sourceRepository.save(Source("https://tech.geoblink.com/feed/"))
      sourceRepository.save(Source("http://tech.gilt.com/rss"))
      sourceRepository.save(Source("https://engineering.giphy.com/rss"))
      sourceRepository.save(Source("https://githubengineering.com/atom.xml"))
      sourceRepository.save(Source("https://blog.github.com/feed.xml"))
      sourceRepository.save(Source("https://gocardless.com/blog/atom.xml"))
      sourceRepository.save(Source("https://team.goodeggs.com/feed"))
      sourceRepository.save(Source("https://security.googleblog.com/feeds/posts/default"))
      sourceRepository.save(Source("http://ai.googleblog.com/feeds/posts/default"))
      sourceRepository.save(Source("https://engineering.gosquared.com/feed"))
      sourceRepository.save(Source("https://blog.gojekengineering.com/feed"))
      sourceRepository.save(Source("http://engineering.grab.com/feed.xml"))
      sourceRepository.save(Source("https://grafana.com/blog/blog/index.xml"))
      sourceRepository.save(Source("https://tech.grammarly.com/feed.xml"))
      sourceRepository.save(Source("https://lambda.grofers.com/feed"))
      sourceRepository.save(Source("http://blog.joingrouper.com/rss"))
      sourceRepository.save(Source("https://engineering.groupon.com/feed/"))
      sourceRepository.save(Source("https://www.theguardian.com/info/series/digital-blog/rss"))
      sourceRepository.save(Source("https://engineering.gusto.com/rss/"))
      sourceRepository.save(Source("http://engineering.hackerearth.com/rss"))
      sourceRepository.save(Source("https://haptik.ai/tech/feed/"))
      sourceRepository.save(Source("http://engineering.harrys.com/feed.xml"))
      sourceRepository.save(Source("https://hashnode.blog/feed"))
      sourceRepository.save(Source("https://hashrocket.com/blog.rss"))
      sourceRepository.save(Source("https://engineering.haus.com/feed"))
      sourceRepository.save(Source("https://heapanalytics.com/blog/category/engineering/feed"))
      sourceRepository.save(Source("https://developer.here.com/blog/feed"))
      sourceRepository.save(Source("https://blog.heroku.com/engineering"))
      sourceRepository.save(Source("http://code.hireart.com/feed.xml"))
      sourceRepository.save(Source("https://medium.com/feed/homeaway-tech-blog"))
      sourceRepository.save(Source("http://blog.honeybadger.io/feed.xml"))
      sourceRepository.save(Source("http://code.hootsuite.com/rss"))
      sourceRepository.save(Source("https://www.hostinger.com/blog/feed/"))
      sourceRepository.save(Source("https://medium.com/feed/engineering-housing"))
      sourceRepository.save(Source("https://product.hubspot.com/blog/rss.xml"))
      sourceRepository.save(Source("https://developer.ibm.com/dwblog/feed/"))
      sourceRepository.save(Source("http://engineering.ifttt.com/feed.xml"))
      sourceRepository.save(Source("https://engineering.imvu.com/feed/"))
      sourceRepository.save(Source("https://blog.imaginea.com/feed/"))
      sourceRepository.save(Source("https://blog.imgur.com/feed/"))
      sourceRepository.save(Source("http://engineering.indeedblog.com/feed/"))
      sourceRepository.save(Source("https://tech.instacart.com/feed"))
      sourceRepository.save(Source("https://instagram-engineering.com/feed"))
      sourceRepository.save(Source("https://software.intel.com/en-us/blogs/feed"))
      sourceRepository.save(Source("http://engineering.intenthq.com/feed.xml"))
      sourceRepository.save(Source("http://intentmedia.com/feed/"))
      sourceRepository.save(Source("https://engineering.intercom.io/feed.xml"))
      sourceRepository.save(Source("https://quickbooks-engineering.intuit.com/feed"))
      sourceRepository.save(Source("http://engineering.invisionapp.com/index.xml"))
      sourceRepository.save(Source("https://blogs.janestreet.com/feed.xml"))
      sourceRepository.save(Source("https://medium.com/feed/jettech"))
      sourceRepository.save(Source("https://jobandtalent.engineering/feed"))
      sourceRepository.save(Source("https://medium.com/feed/jobteaser-dev-team"))
      sourceRepository.save(Source("https://jollygoodcode.github.io/atom.xml"))
      sourceRepository.save(Source("https://tech.just-eat.com/feed/"))
      sourceRepository.save(Source("http://engineering.khanacademy.org/rss.xml"))
      sourceRepository.save(Source("https://kickstarter.engineering/feed"))
      sourceRepository.save(Source("https://techblog.king.com/feed/"))
      sourceRepository.save(Source("https://kinvolk.io/blog/index.xml"))
      sourceRepository.save(Source("https://devblog.kogan.com/blog?format=RSS"))
      sourceRepository.save(Source("https://kolosek.com/rss/"))
      sourceRepository.save(Source("https://latacora.micro.blog/feed.xml"))
      sourceRepository.save(Source("http://engineering.laterooms.com/rss/"))
      sourceRepository.save(Source("https://tech.lendinghome.com/feed"))
      sourceRepository.save(Source("https://engineering.linecorp.com/en/blog/rss2"))
      sourceRepository.save(Source("https://developers.livechatinc.com/blog/rss"))
      sourceRepository.save(Source("https://liveramp.com/engineering/feed/"))
      sourceRepository.save(Source("https://eng.localytics.com/rss/"))
      sourceRepository.save(Source("https://eng.lyft.com/feed"))
      sourceRepository.save(Source("http://www.madetech.com/feed"))
      sourceRepository.save(Source("http://blog.mallow-tech.com/feed/"))
      sourceRepository.save(Source("https://devs.mailchimp.com/blog/feed/"))
      sourceRepository.save(Source("http://blog.mandrill.com/feeds/all.atom.xml"))
      sourceRepository.save(Source("https://www.maptiler.com/blog/feed/posts.xml"))
      sourceRepository.save(Source("https://medium.engineering/feed"))
      sourceRepository.save(Source("http://blog.memsql.com/feed/"))
      sourceRepository.save(Source("https://mesosphere.com/feed/"))
      sourceRepository.save(Source("http://blogs.msdn.microsoft.com/pythonengineering/feed/"))
      sourceRepository.save(Source("https://mixmax.com/rss/"))
      sourceRepository.save(Source("https://engineering.mixpanel.com/feed/"))
      sourceRepository.save(Source("https://engineering.mongodb.com/post?format=RSS"))
      sourceRepository.save(Source("http://engineering.monsanto.com/feed.xml"))
      sourceRepository.save(Source("https://blog.moove-it.com/rss"))
      sourceRepository.save(Source("http://planet.mozilla.org/ateam/atom.xml"))
      sourceRepository.save(Source("https://hacks.mozilla.org/feed/"))
      sourceRepository.save(Source("http://planet.mozilla.org/releng/atom.xml"))
      sourceRepository.save(Source("https://medium.com/feed/myntra-engineering"))
      sourceRepository.save(Source("http://sartorialscience.myntrablogs.com/atom.xml"))
      sourceRepository.save(Source("https://medium.com/feed/netflix-techblog"))
      sourceRepository.save(Source("https://open.nytimes.com/feed"))
      sourceRepository.save(Source("https://engblog.nextdoor.com/feed"))
      sourceRepository.save(Source("https://nordicapis.com/feed/"))
      sourceRepository.save(Source("https://blog.novoda.com/rss/"))
      sourceRepository.save(Source("http://blog.apps.npr.org/atom.xml"))
      sourceRepository.save(Source("https://blogs.nvidia.com/feed/"))
      sourceRepository.save(Source("https://blog.octo.com/en/feed/"))
      sourceRepository.save(Source("https://developer.okta.com/feed.xml"))
      sourceRepository.save(Source("https://tech.olx.com/feed"))
      sourceRepository.save(Source("https://umbrella.cisco.com/blog/feed/"))
      sourceRepository.save(Source("http://tech.opentable.com/feed/"))
      sourceRepository.save(Source("http://tech.opentable.co.uk/atom.xml"))
      sourceRepository.save(Source("https://code.oursky.com/feed/"))
      sourceRepository.save(Source("http://tech.oyster.com/atom.xml"))
      sourceRepository.save(Source("http://engineering.opensooq.com/feed/"))
      sourceRepository.save(Source("https://engineering.panoramaed.com/feed/"))
      sourceRepository.save(Source("https://www.paypal-engineering.com/feed/"))
      sourceRepository.save(Source("https://s3-us-west-1.amazonaws.com/periscope-rss/rss.xml"))
      sourceRepository.save(Source("https://tech.pic-collage.com/feed"))
      sourceRepository.save(Source("https://medium.com/feed/@Pinterest_Engineering"))
      sourceRepository.save(Source("http://feeds.feedburner.com/PivotalEngineeringJournal"))
      sourceRepository.save(Source("https://postmarkapp.com/blog/feed.atom"))
      sourceRepository.save(Source("https://medium.com/feed/postmates-blog/tagged/engineering"))
      sourceRepository.save(Source("https://engineering.prezi.com/feed"))
      sourceRepository.save(Source("https://www.pubnub.com/blog/feed/"))
      sourceRepository.save(Source("http://blog.8thcolor.com/feed.xml"))
      sourceRepository.save(Source("https://making.pusher.com/feed.xml"))
      sourceRepository.save(Source("https://www.raizlabs.com/dev/feed/"))
      sourceRepository.save(Source("https://blog.rapidapi.com/feed/"))
      sourceRepository.save(Source("http://rea.tech/feed/"))
      sourceRepository.save(Source("https://realm.io/feed.xml"))
      sourceRepository.save(Source("http://artplustech.com/feed/"))
      sourceRepository.save(Source("http://redino.net/blog/feed/"))
      sourceRepository.save(Source("https://developers.redhat.com/blog/feed/atom/"))
      sourceRepository.save(Source("http://engineering.remind.com/feed.xml"))
      sourceRepository.save(Source("https://medium.com/feed/retailmenot-engineering"))
      sourceRepository.save(Source("http://eng.rightscale.com/feed.xml"))
      sourceRepository.save(Source("https://engineering.riotgames.com/rss.xml"))
      sourceRepository.save(Source("https://blog.risingstack.com/rss/"))
      sourceRepository.save(Source("https://www.rosehosting.com/blog/feed/"))
      sourceRepository.save(Source("https://www.runtastic.com/blog/en/feed/"))
      sourceRepository.save(Source("https://developer.salesforce.com/blogs/feed"))
      sourceRepository.save(Source("http://www.schibsted.pl/blog/feed/"))
      sourceRepository.save(Source("https://blog.scrapinghub.com/rss.xml"))
      sourceRepository.save(Source("https://tech.scrunch.com/blog/feeds/rss/"))
      sourceRepository.save(Source("http://tech.secretescapes.com/feed/"))
      sourceRepository.save(Source("https://segment.com/blog/atom.xml"))
      sourceRepository.save(Source("https://engineering.semantics3.com/feed"))
      sourceRepository.save(Source("https://semaphoreci.com/community/tutorials.atom"))
      sourceRepository.save(Source("http://semaphoreci.com/blog/engineering.xml"))
      sourceRepository.save(Source("http://blog.sensible.io/rss"))
      sourceRepository.save(Source("https://serverless.com/blog/feed.xml"))
      sourceRepository.save(Source("https://engineroom.settled.co.uk/feed"))
      sourceRepository.save(Source("http://engineering.shapesecurity.com/rss"))
      sourceRepository.save(Source("https://www.sharethis.com/feed/"))
      sourceRepository.save(Source("https://blog.shazam.com/feed"))
      sourceRepository.save(Source("http://engineering.shopify.com/blogs/engineering.atom"))
      sourceRepository.save(Source("https://tech.showmax.com/feed.xml"))
      sourceRepository.save(Source("https://medium.com/feed/shyp-engineering"))
      sourceRepository.save(Source("https://blog.siftscience.com/feed/"))
      sourceRepository.save(Source("https://www.sitepoint.com/feed/"))
      sourceRepository.save(Source("https://technology.skybettingandgaming.com/feed.xml"))
      sourceRepository.save(Source("https://medium.com/feed/@SkyscannerEng"))
      sourceRepository.save(Source("https://slack.engineering/feed"))
      sourceRepository.save(Source("https://tech.small-improvements.com/rss"))
      sourceRepository.save(Source("https://up.smartrecruiters.com/feed"))
      sourceRepository.save(Source("https://snyk.io/blog/feed.xml"))
      sourceRepository.save(Source("https://devblog.songkick.com/feed"))
      sourceRepository.save(Source("https://blog.soshace.com/en/feed/"))
      sourceRepository.save(Source("https://developers.soundcloud.com/blog.rss"))
      sourceRepository.save(Source("http://engineering.speedledger.com/feed/"))
      sourceRepository.save(Source("https://labs.spotify.com/feed/"))
      sourceRepository.save(Source("https://blog.sqreen.io/feed/"))
      sourceRepository.save(Source("https://medium.com/feed/square-corner-blog"))
      sourceRepository.save(Source("https://engineering.squarespace.com/blog?format=RSS"))
      sourceRepository.save(Source("https://stackoverflow.blog/engineering/feed/"))
      sourceRepository.save(Source("https://multithreaded.stitchfix.com/feed.xml"))
      sourceRepository.save(Source("https://stormpath.com/feed"))
      sourceRepository.save(Source("https://medium.com/feed/strava-engineering"))
      sourceRepository.save(Source("https://www.stridenyc.com/blog/rss.xml"))
      sourceRepository.save(Source("https://stripe.com/blog/feed.rss"))
      sourceRepository.save(Source("https://www.surveymonkey.com/feed/"))
      sourceRepository.save(Source("https://blog.takipi.com/feed/"))
      sourceRepository.save(Source("https://target.github.io/feed.xml"))
      sourceRepository.save(Source("http://tech.taskrabbit.com/feed.xml"))
      sourceRepository.save(Source("https://engineroom.teamwork.com/feed"))
      sourceRepository.save(Source("http://teespring.engineering/index.xml"))
      sourceRepository.save(Source("http://techblog.thescore.com/feed.xml"))
      sourceRepository.save(Source("https://feeds.feedburner.com/GiantRobotsSmashingIntoOtherGiantRobots"))
      sourceRepository.save(Source("https://www.thoughtworks.com/rss/insights.xml"))
      sourceRepository.save(Source("https://www.thumbtack.com/engineering/feed/"))
      sourceRepository.save(Source("https://tech.ticketmaster.com/feed/"))
      sourceRepository.save(Source("https://blog.timescale.com/feed"))
      sourceRepository.save(Source("https://tech.gotinder.com/rss/"))
      sourceRepository.save(Source("https://www.toptal.com/blog.rss"))
      sourceRepository.save(Source("http://engineroom.trackmaven.com/feeds/rss.xml"))
      sourceRepository.save(Source("https://tech.transferwise.com/rss/"))
      sourceRepository.save(Source("https://tech.trello.com/feed.xml"))
      sourceRepository.save(Source("http://engineering.tripadvisor.com/rss"))
      sourceRepository.save(Source("https://tech.trivago.com/index.xml"))
      sourceRepository.save(Source("https://www.drivenbycode.com/feed/"))
      sourceRepository.save(Source("https://engineering.tumblr.com/rss"))
      sourceRepository.save(Source("https://www.twilio.com/blog/feed"))
      sourceRepository.save(Source("https://blog.twitter.com/engineering/feed"))
      sourceRepository.save(Source("https://medium.com/feed/twitch-news/tagged/engineering"))
      sourceRepository.save(Source("https://eng.uber.com/feed/"))
      sourceRepository.save(Source("https://engineering.universe.com/feed"))
      sourceRepository.save(Source("https://upday.github.io/feed.xml"))
      sourceRepository.save(Source("https://engineering.upgrad.com/feed"))
      sourceRepository.save(Source("https://engineering.vena.io/rss/"))
      sourceRepository.save(Source("http://blog.venmo.com/hf2t3h4x98p5e13z82pl8j66ngcmry?format=RSS"))
      sourceRepository.save(Source("https://blog.versioneye.com/feed/"))
      sourceRepository.save(Source("https://medium.com/feed/vevo-engineering"))
      sourceRepository.save(Source("http://engineering.vine.co/rss"))
      sourceRepository.save(Source("http://engineering.vinted.com//atom.xml"))
      sourceRepository.save(Source("http://blog.vngrs.com/rss.xml"))
      sourceRepository.save(Source("https://buildingvts.com/feed"))
      sourceRepository.save(Source("https://medium.com/feed/walmartlabs"))
      sourceRepository.save(Source("http://engineering.wattpad.com/rss"))
      sourceRepository.save(Source("https://tech.wayfair.com/feed/"))
      sourceRepository.save(Source("http://eng.wealthfront.com/feed/"))
      sourceRepository.save(Source("https://blog.wearewizards.io/all.atom.xml"))
      sourceRepository.save(Source("https://engineering.webengage.com/feed/"))
      sourceRepository.save(Source("https://medium.com/feed/wemake-services"))
      sourceRepository.save(Source("https://wecode.wepay.com/feed.xml"))
      sourceRepository.save(Source("http://tech.wimdu.com/rss"))
      sourceRepository.save(Source("http://engineering.wingify.com/atom.xml"))
      sourceRepository.save(Source("https://medium.com/feed/@WoloxEngineering"))
      sourceRepository.save(Source("http://development.wombatsecurity.com/feed.xml"))
      sourceRepository.save(Source("http://wongatech.github.io/feed.xml"))
      sourceRepository.save(Source("https://wyeworks.com/blog/atom.xml"))
      sourceRepository.save(Source("https://tech.xing.com/feed"))
      sourceRepository.save(Source("https://xmartlabs.com/feed.xml"))
      sourceRepository.save(Source("https://yahooeng.tumblr.com/rss"))
      sourceRepository.save(Source("https://medium.com/feed/yammer-engineering"))
      sourceRepository.save(Source("https://engineeringblog.yelp.com/feed.xml"))
      sourceRepository.save(Source("https://medium.com/feed/yld-engineering-blog"))
      sourceRepository.save(Source("https://zeemee.engineering/feed"))
      sourceRepository.save(Source("https://medium.com/feed/zendesk-engineering"))
      sourceRepository.save(Source("https://developerblog.zendesk.com/feed"))
      sourceRepository.save(Source("https://engineering.zenefits.com/feed/"))
      sourceRepository.save(Source("https://www.zillow.com/engineering/rss"))
      sourceRepository.save(Source("https://engineering.zomato.com/rss"))
      sourceRepository.save(Source("https://medium.com/feed/zoosk-engineering"))
      sourceRepository.save(Source("https://zulily-tech.com/feed/"))
      sourceRepository.save(Source("http://feeds.feedburner.com/zumba_engineering"))
      sourceRepository.save(Source("https://0xadada.pub/feed.xml"))
      sourceRepository.save(Source("http://tenderlovemaking.com/atom.xml"))
      sourceRepository.save(Source("https://blogs.msdn.microsoft.com/abhinaba/feed/"))
      sourceRepository.save(Source("http://masnun.com/feed"))
      sourceRepository.save(Source("https://adambard.com/blog/feed.xml"))
      sourceRepository.save(Source("http://dtrace.org/blogs/ahl/feed/"))
      sourceRepository.save(Source("http://www.adamtuliper.com/feeds/posts/default"))
      sourceRepository.save(Source("http://addyosmani.com/rss.xml"))
      sourceRepository.save(Source("https://blog.acolyer.org/feed/"))
      sourceRepository.save(Source("https://alanstorm.com/feed/feed.xml"))
      sourceRepository.save(Source("http://arogozhnikov.github.io/feed.xml"))
      sourceRepository.save(Source("https://infrequently.org/feed/"))
      sourceRepository.save(Source("http://akaptur.com/atom.xml"))
      sourceRepository.save(Source("https://www.amitmerchant.com/feed.xml"))
      sourceRepository.save(Source("http://aarvik.dk/rss/"))
      sourceRepository.save(Source("https://computer.forensikblog.de/en/atom.xml"))
      sourceRepository.save(Source("https://www.andrewcbancroft.com/feed/"))
      sourceRepository.save(Source("https://blog.bramp.net/index.xml"))
      sourceRepository.save(Source("http://blog.andrewray.me/rss/"))
      sourceRepository.save(Source("http://aakinshin.net/en/rss.xml"))
      sourceRepository.save(Source("http://antirez.com/rss"))
      sourceRepository.save(Source("https://www.devroom.io/index.xml"))
      sourceRepository.save(Source("https://ariya.io/index.xml"))
      sourceRepository.save(Source("http://lucumr.pocoo.org/feed.atom"))
      sourceRepository.save(Source("http://feeds.feedburner.com/2ality"))
      sourceRepository.save(Source("http://bad-concurrency.blogspot.com/feeds/posts/default"))
      sourceRepository.save(Source("http://www.wefearchange.org/feeds/all.atom.xml"))
      sourceRepository.save(Source("https://www.bfilipek.com/feeds/posts/default"))
      sourceRepository.save(Source("https://benmccormick.org/feed.json"))
      sourceRepository.save(Source("http://www.billthelizard.com/feeds/posts/default"))
      sourceRepository.save(Source("https://bjornjohansen.no/feed"))
      sourceRepository.save(Source("https://blog.blakeerickson.com/feed.xml"))
      sourceRepository.save(Source("http://blog.blundellapps.co.uk/feed/"))
      sourceRepository.save(Source("https://bohops.com/feed/"))
      sourceRepository.save(Source("http://rhodesmill.org/brandon/feed"))
      sourceRepository.save(Source("https://brendaneich.com/feed/"))
      sourceRepository.save(Source("http://www.brendangregg.com/blog/rss.xml"))
      sourceRepository.save(Source("https://medium.com/feed/@elbrujohalcon"))
      sourceRepository.save(Source("http://dtrace.org/blogs/bmc/feed/"))
      sourceRepository.save(Source("https://carlosbecker.com/index.xml"))
      sourceRepository.save(Source("https://www.chenhuijing.com/feed.xml"))
      sourceRepository.save(Source("http://thelazylog.com/rss/"))
      sourceRepository.save(Source("https://www.metachris.com/index.xml"))
      sourceRepository.save(Source("http://nullprogram.com/feed/"))
      sourceRepository.save(Source("http://blog.claymcleod.io/atom.xml"))
      sourceRepository.save(Source("http://www.cimgf.com/feed/"))
      sourceRepository.save(Source("https://codewithstyle.info/feed/"))
      sourceRepository.save(Source("https://tympanus.net/codrops/rss"))
      sourceRepository.save(Source("https://medium.com/feed/dailyjs"))
      sourceRepository.save(Source("http://dailytechvideo.com/feed/"))
      sourceRepository.save(Source("https://danluu.com/atom.xml"))
      sourceRepository.save(Source("https://code.dblock.org/feed.xml"))
      sourceRepository.save(Source("https://medium.com/feed/@dschmidt1992"))
      sourceRepository.save(Source("https://www.datchley.name/rss/"))
      sourceRepository.save(Source("https://dave.cheney.net/feed"))
      sourceRepository.save(Source("https://davidwalsh.name/feed/atom"))
      sourceRepository.save(Source("https://deanhume.com/rss/"))
      sourceRepository.save(Source("http://deborah-digges.github.io/atom.xml"))
      sourceRepository.save(Source("https://hookrace.net/blog/feed/"))
      sourceRepository.save(Source("https://yurichev.com/blog/rss.xml"))
      sourceRepository.save(Source("https://www.dereuromark.de/feed/"))
      sourceRepository.save(Source("https://www.discovermeteor.com/feed.xml"))
      sourceRepository.save(Source("https://domenicoluciani.com/feed.xml"))
      sourceRepository.save(Source("https://dotdev.co/feed/"))
      sourceRepository.save(Source("https://dragan.rocks/feed.xml"))
      sourceRepository.save(Source("https://www.gajotres.net/feed/"))
      sourceRepository.save(Source("https://drewdevault.com/feed.xml"))
      sourceRepository.save(Source("http://www.practicallyefficient.com/feed.xml"))
      sourceRepository.save(Source("https://hyegar.com/rss.xml"))
      sourceRepository.save(Source("https://eaf4.com/rss"))
      sourceRepository.save(Source("https://elegantcode.com/feed/"))
      sourceRepository.save(Source("https://eli.thegreenplace.net/feeds/all.atom.xml"))
      sourceRepository.save(Source("https://medium.com/feed/javascript-scene"))
      sourceRepository.save(Source("https://ericlippert.com/feed/"))
      sourceRepository.save(Source("https://erikrunyon.com/feed.xml"))
      sourceRepository.save(Source("https://evanhahn.com/feed.xml"))
      sourceRepository.save(Source("http://www.evanjones.ca/index.rss"))
      sourceRepository.save(Source("http://www.evanmiller.org/news.xml"))
      sourceRepository.save(Source("https://blog.evantahler.com/feed"))
      sourceRepository.save(Source("http://fbrnc.net/blog.atom"))
      sourceRepository.save(Source("https://blog.fedecarg.com/feed/"))
      sourceRepository.save(Source("https://tomassetti.me/feed/"))
      sourceRepository.save(Source("https://blog.filippo.io/rss/"))
      sourceRepository.save(Source("https://murze.be/feed"))
      sourceRepository.save(Source("https://glebbahmutov.com/blog/atom.xml"))
      sourceRepository.save(Source("https://www.darkcoding.net/feed/"))
      sourceRepository.save(Source("http://neopythonic.blogspot.com/feeds/posts/default"))
      sourceRepository.save(Source("https://firstdoit.com/feed"))
      sourceRepository.save(Source("https://haydenjames.io/rss"))
      sourceRepository.save(Source("https://conductofcode.io/feed.xml"))
      sourceRepository.save(Source("https://henrikwarne.com/feed/"))
      sourceRepository.save(Source("http://feeds.feedburner.com/HighScalability"))
      sourceRepository.save(Source("http://huonw.github.io/blog/atom.xml"))
      sourceRepository.save(Source("https://blog.hypriot.com/index.xml"))
      sourceRepository.save(Source("https://themodernlife.github.io/feed.xml"))
      sourceRepository.save(Source("http://iansommerville.com/systems-software-and-technology/feed/"))
      sourceRepository.save(Source("https://idontgetoutmuch.wordpress.com/feed/"))
      sourceRepository.save(Source("http://stdout.in/en/cat/all.rss"))
      sourceRepository.save(Source("http://ieftimov.com/feed.xml"))
      sourceRepository.save(Source("https://www.igvita.com/feed/"))
      sourceRepository.save(Source("https://ivanursul.com/feed.xml"))
      sourceRepository.save(Source("https://jack.ofspades.com/rss/index.html"))
      sourceRepository.save(Source("https://jaketrent.com/index.xml"))
      sourceRepository.save(Source("http://jakewharton.com/feed.xml"))
      sourceRepository.save(Source("http://jakeyesbeck.com/atom.xml"))
      sourceRepository.save(Source("http://prog21.dadgum.com/atom.xml"))
      sourceRepository.save(Source("http://feedpress.me/jlongster"))
      sourceRepository.save(Source("http://feeds.feedburner.com/buckblog"))
      sourceRepository.save(Source("https://idiosyncratic-ruby.com/feed.xml"))
      sourceRepository.save(Source("http://blog.jayfields.com/feeds/posts/default"))
      sourceRepository.save(Source("http://feeds.feedburner.com/codinghorror"))
      sourceRepository.save(Source("http://preshing.com/feed"))
      sourceRepository.save(Source("https://jeremykun.com/feed/"))
      sourceRepository.save(Source("https://jerrygamblin.com/feed/"))
      sourceRepository.save(Source("https://blog.jessfraz.com/index.xml"))
      sourceRepository.save(Source("http://www.blackbytes.info/rss"))
      sourceRepository.save(Source("https://begriffs.com/atom.xml"))
      sourceRepository.save(Source("https://www.joelonsoftware.com/feed/"))
      sourceRepository.save(Source("http://johannesbrodwall.com/feed/"))
      sourceRepository.save(Source("https://feeds.feedburner.com/JohnResig"))
      sourceRepository.save(Source("https://www.johnwittenauer.net/rss/"))
      sourceRepository.save(Source("http://www.jonkensy.com/feed/"))
      sourceRepository.save(Source("https://codeblog.jonskeet.uk/feed/"))
      sourceRepository.save(Source("https://blog.cugu.eu/index.xml"))
      sourceRepository.save(Source("http://www.born2data.com/feed_atom.xml"))
      sourceRepository.save(Source("https://snook.ca/jonathan/index.rdf"))
      sourceRepository.save(Source("http://blog.reverberate.org/feed.xml"))
      sourceRepository.save(Source("https://joshtronic.com/atom.xml"))
      sourceRepository.save(Source("https://jtreminio.com/atom.xml"))
      sourceRepository.save(Source("https://jvns.ca/atom.xml"))
      sourceRepository.save(Source("https://www.justinweiss.com/atom.xml"))
      sourceRepository.save(Source("https://feeds.feedburner.com/juristrumpflohner"))
      sourceRepository.save(Source("https://useyourloaf.com/blog/rss.xml"))
      sourceRepository.save(Source("https://kev.inburke.com/feed/"))
      sourceRepository.save(Source("https://medium.com/feed/@kirill_shevch"))
      sourceRepository.save(Source("https://aphyr.com/posts.atom"))
      sourceRepository.save(Source("http://lambda-the-ultimate.org/rss.xml"))
      sourceRepository.save(Source("http://lg.io/feed.xml"))
      sourceRepository.save(Source("https://iridakos.com/feed.xml"))
      sourceRepository.save(Source("http://lea.verou.me/feed/"))
      sourceRepository.save(Source("http://blog.lerner.co.il/feed/"))
      sourceRepository.save(Source("http://lifepluslinux.blogspot.com/feeds/posts/default"))
      sourceRepository.save(Source("http://loige.co/rss/"))
      sourceRepository.save(Source("http://manu.sporny.org/feed/"))
      sourceRepository.save(Source("https://enoent.fr/atom.xml"))
      sourceRepository.save(Source("https://blog.rinesi.com/feed/"))
      sourceRepository.save(Source("https://ocramius.github.io/atom.xml"))
      sourceRepository.save(Source("https://idea.popcount.org/rss.xml"))
      sourceRepository.save(Source("http://lackingrhoticity.blogspot.com/feeds/posts/default"))
      sourceRepository.save(Source("https://martinfowler.com/feed.atom"))
      sourceRepository.save(Source("https://maryrosecook.com/blog/feed.xml"))
      sourceRepository.save(Source("https://matt.aimonetti.net/atom.xml"))
      sourceRepository.save(Source("https://www.mattcutts.com/blog/feed/"))
      sourceRepository.save(Source("http://matt.might.net/articles/feed.rss"))
      sourceRepository.save(Source("http://mattwarren.org/atom.xml"))
      sourceRepository.save(Source("https://blog.cryptographyengineering.com/feed/"))
      sourceRepository.save(Source("https://www.michaelcrump.net/feed.xml"))
      sourceRepository.save(Source("http://www.michaelgallego.fr/feed.xml"))
      sourceRepository.save(Source("http://mherman.org/feed.xml"))
      sourceRepository.save(Source("https://www.miqu.me/atom.xml"))
      sourceRepository.save(Source("http://www.mikeash.com/pyblog/rss.py"))
      sourceRepository.save(Source("http://blog.fogus.me/feed/"))
      sourceRepository.save(Source("https://blog.sleeplessbeastie.eu/feed.xml"))
      sourceRepository.save(Source("https://mirocupak.com/feed.xml"))
      sourceRepository.save(Source("https://meowni.ca/atom.xml"))
      sourceRepository.save(Source("https://blog.monstermuffin.org/feed/"))
      sourceRepository.save(Source("http://feeds.feedburner.com/mishadoff"))
      sourceRepository.save(Source("https://natashatherobot.com/rss"))
      sourceRepository.save(Source("https://blog.nelhage.com/atom.xml"))
      sourceRepository.save(Source("https://www.thepolyglotdeveloper.com/index.xml"))
      sourceRepository.save(Source("https://nickcraver.com/blog/feed.xml"))
      sourceRepository.save(Source("https://nickdesaulniers.github.io/atom.xml"))
      sourceRepository.save(Source("https://www.client9.com/index.xml"))
      sourceRepository.save(Source("http://blog.thislongrun.com/feeds/posts/default"))
      sourceRepository.save(Source("http://blog.codefx.org/feed/"))
      sourceRepository.save(Source("http://www.nikola-breznjak.com/blog/feed/atom/"))
      sourceRepository.save(Source("http://nikolay.rocks/atom.xml"))
      sourceRepository.save(Source("https://nshipster.com/feed.xml"))
      sourceRepository.save(Source("https://www.nateberkopec.com/feed.xml"))
      sourceRepository.save(Source("https://fullstack.info/feed/"))
      sourceRepository.save(Source("https://oleb.net/blog/atom.xml"))
      sourceRepository.save(Source("http://www.windytan.com/feeds/posts/default"))
      sourceRepository.save(Source("http://blog.pamelafox.org/feeds/posts/default"))
      sourceRepository.save(Source("http://feeds2.feedburner.com/patshaughnessy"))
      sourceRepository.save(Source("http://www.aaronsw.com/2002/feeds/pgessays.rss"))
      sourceRepository.save(Source("https://feeds.feedburner.com/paul-irish"))
      sourceRepository.save(Source("https://aerotwist.com/blog/feed/"))
      sourceRepository.save(Source("https://blog.pchudzik.com/index.xml"))
      sourceRepository.save(Source("http://www.norvig.com/rss-feed.xml"))
      sourceRepository.save(Source("http://petersteinberger.com/atom.xml"))
      sourceRepository.save(Source("http://www.catonmat.net/feed/"))
      sourceRepository.save(Source("https://petr-mitrichev.blogspot.com/feeds/posts/default"))
      sourceRepository.save(Source("https://feeds.feedburner.com/philipwalton"))
      sourceRepository.save(Source("https://os.phil-opp.com/atom.xml"))
      sourceRepository.save(Source("https://feeds.feedburner.com/ponyfoo"))
      sourceRepository.save(Source("http://piotrpasich.com/feed/"))
      sourceRepository.save(Source("http://blog.wittchen.biz.pl/feed.xml"))
      sourceRepository.save(Source("https://rachelbythebay.com/w/atom.xml"))
      sourceRepository.save(Source("http://radek.io/rss.xml"))
      sourceRepository.save(Source("https://radimrehurek.com/feed/"))
      sourceRepository.save(Source("https://nativeguru.wordpress.com/feed/"))
      sourceRepository.save(Source("https://www.raywenderlich.com/rss"))
      sourceRepository.save(Source("https://blogs.msdn.microsoft.com/oldnewthing/feed"))
      sourceRepository.save(Source("https://rhettinger.wordpress.com/feed/"))
      sourceRepository.save(Source("https://reactjsnews.com/feed.xml"))
      sourceRepository.save(Source("https://realpython.com/atom.xml"))
      sourceRepository.save(Source("http://raganwald.com/atom.xml"))
      sourceRepository.save(Source("http://feeds.regulargeek.com/RegularGeek"))
      sourceRepository.save(Source("https://akrabat.com/feed/"))
      sourceRepository.save(Source("http://blog.cleancoder.com/atom.xml"))
      sourceRepository.save(Source("https://eviltrout.com/feed.xml"))
      sourceRepository.save(Source("http://blog.rtwilson.com/feed/"))
      sourceRepository.save(Source("http://www.rudyhuyn.com/blog/feed/"))
      sourceRepository.save(Source("https://neverfriday.com/feed/"))
      sourceRepository.save(Source("https://ruslanspivak.com/feeds/all.atom.xml"))
      sourceRepository.save(Source("https://www.sakib.ninja/rss/"))
      sourceRepository.save(Source("http://samsaffron.com/posts.rss"))
      sourceRepository.save(Source("http://sergeyzhuk.me/feed.xml"))
      sourceRepository.save(Source("http://feeds.hanselman.com/ScottHanselman"))
      sourceRepository.save(Source("http://fuzzyblog.io//blog/feed.xml"))
      sourceRepository.save(Source("https://devdactic.com/feed/"))
      sourceRepository.save(Source("https://www.9lessons.info/feeds/posts/default"))
      sourceRepository.save(Source("http://stackabuse.com/rss/"))
      sourceRepository.save(Source("http://codebeforethehorse.tumblr.com/rss"))
      sourceRepository.save(Source("http://blog.joda.org/feeds/posts/default"))
      sourceRepository.save(Source("https://www.cs.columbia.edu/~smb/blog/control/blog.xml"))
      sourceRepository.save(Source("https://steve-yegge.blogspot.com/feeds/posts/default"))
      sourceRepository.save(Source("http://sudhagar.com/feed.xml"))
      sourceRepository.save(Source("https://swizec.com/blog/feed"))
      sourceRepository.save(Source("http://teropa.info/blog/feed.xml"))
      sourceRepository.save(Source("https://thatthinginswift.com/index.xml"))
      sourceRepository.save(Source("https://thecodedself.github.io/feed.xml"))
      sourceRepository.save(Source("http://thedailywtf.com/rss"))
      sourceRepository.save(Source("http://upcoder.com/feed"))
      sourceRepository.save(Source("http://jelv.is/blog/rss.xml"))
      sourceRepository.save(Source("https://toddmotto.com/feed.xml"))
      sourceRepository.save(Source("http://www.tjmaher.com/feeds/posts/default"))
      sourceRepository.save(Source("https://una.im/feed.xml"))
      sourceRepository.save(Source("https://undocumentedmatlab.com/feed"))
      sourceRepository.save(Source("http://vanillajava.blogspot.com/feeds/posts/default"))
      sourceRepository.save(Source("https://vladmihalcea.com/feed/"))
      sourceRepository.save(Source("http://www.wilfred.me.uk/rss.xml"))
      sourceRepository.save(Source("https://www.ardanlabs.com/blog/index.xml"))
      sourceRepository.save(Source("http://www.afronski.pl/feed.xml"))
      sourceRepository.save(Source("https://www.yegor256.com/rss.xml"))
      sourceRepository.save(Source("http://yifan.lu/feed.xml"))
      sourceRepository.save(Source("https://zachholman.com/atom.xml"))
      sourceRepository.save(Source("https://zolmeister.com/feeds/posts/default"))
      sourceRepository.save(Source("https://android-developers.googleblog.com/feeds/posts/default"))
      sourceRepository.save(Source("http://blog.atom.io/feed.xml"))
      sourceRepository.save(Source("https://blog.getbootstrap.com/feed.xml"))
      sourceRepository.save(Source("https://crystal-lang.org/feed.xml"))
      sourceRepository.save(Source("https://blog.golang.org/feed.atom"))
      sourceRepository.save(Source("https://ipfs.io/blog/index.xml"))
      sourceRepository.save(Source("https://blog.jooq.org/feed/"))
      sourceRepository.save(Source("http://blog.klipse.tech//feed.xml"))
      sourceRepository.save(Source("https://blog.jetbrains.com/kotlin/feed/"))
      sourceRepository.save(Source("https://feed.laravel-news.com/"))
      sourceRepository.save(Source("https://blogs.windows.com/msedgedev/rss"))
      sourceRepository.save(Source("https://blogs.msdn.microsoft.com/dotnet/feed/"))
      sourceRepository.save(Source("https://facebook.github.io/feed.xml"))
      sourceRepository.save(Source("https://facebook.github.io/react-native/blog/atom.xml"))
      sourceRepository.save(Source("https://www.red-lang.org/feeds/posts/default"))
      sourceRepository.save(Source("http://rocksdb.org/feed.xml"))
      sourceRepository.save(Source("https://blog.rust-lang.org/feed.xml"))
      sourceRepository.save(Source("https://blog.sketchapp.com/feed"))
      sourceRepository.save(Source("https://developer.apple.com/swift/blog/news.rss"))
      sourceRepository.save(Source("http://www.vertabelo.com/_rss/blog.xml"))
    }

  }

  @Component
  @Profile("dev")
  class ProdInitializer {

    @PostConstruct
    fun init() {
      // todo create admin, ..
    }

  }
}
