package org.migor.feedless

object AppProfiles {
  const val dev = "dev"
  const val serveStatic = "static"
  const val legacyFeeds = "legacy"
  const val analytics = "analytics"
  const val authSSO = "sso"
  const val selfHosted = "selfHosted"
  const val authMail = "mail"
  const val authRoot = "authRoot"
  const val database = "database"
  const val cron = "cron"
  const val mail = "mail"
  const val cache = "cache"
  const val nothrottle = "nothrottle"
  const val community = "community"
  const val scrape = "scrape"
  const val saas = "saas"
  const val prometheus = "prometheus"
  const val agent = "agent"
  const val api = "api"
  const val feed = "feed"
  const val seed = "seed"
  const val legacyV2 = "legacySupport"
  const val autoSignIn = "autoSignIn"
}
