apiVersion: v1
kind: Service
metadata:
  name: local-registry
spec:
  type: NodePort
  selector:
    app: local-registry
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
#      nodePort: 32000  # Access via http://<node-ip>:32000
